### ISSUE TITLE
Split Cling gives infinite clings

### ISSUE THREAD

**Issue by Bloquit2** [pseudoregalia-modding/rando#3] opened 2024-02-09 09:14 UTC
When playing I noticed that i seemed to have infinite clings, It appears this is due to the split cling function.

**Comment by bananaturtlesandwich** [comment] 2024-02-11 21:29
i can't reproduce so could you send `rando_p.pak`? if you go into the program there should be a link to its location

**Comment by Bloquit2** [comment] 2024-02-12 17:30
I seem to now be unable to replicate it myself, unfortunately I make new runs pretty frequently so its gone now, I will keep that in mind for future issues I run across.

**Comment by bananaturtlesandwich** [comment] 2024-02-12 18:20
ok then i'll close it for now then - reopen if you get it again :)

**Closed as completed by bananaturtlesandwich** 2024-02-12 18:20 UTC
